version: '3.8'

services:
  monitor:
    build: .
    container_name: internet_monitor
    volumes:
      - ./log:/app/log
    restart: unless-stopped

  bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: telegram_bot_mon
    working_dir: /app
    command: python -m bot.bot
    env_file:
      - .env
    volumes:
      - ./log:/app/log
    restart: unless-stopped
