version: '3.8'

services:
  monitor:
    build: .
    container_name: internet_monitor
    env_file:
      - .env
    user: root
    volumes:
      - ./log:/app/log
      - /var/run/docker.sock:/var/run/docker.sock
    privileged: true
    networks:
      - tele_vba_bot_default
    restart: unless-stopped

  bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: telegram_bot_mon
    working_dir: /app
    command: python -m bot.bot
    env_file:
      - .env
    volumes:
      - ./log:/app/log
    networks:
      - tele_vba_bot_default
    restart: unless-stopped

networks:
  tele_vba_bot_default:
    external: true
